package com.rws.kittylauncher.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import android.os.SystemClock
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyEventType
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.input.key.type
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.tv.material3.Border
import androidx.tv.material3.ClickableSurfaceDefaults
import androidx.tv.material3.Glow
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import androidx.compose.foundation.BorderStroke
import com.rws.kittylauncher.data.AppEntry
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.interaction.collectIsFocusedAsState
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.foundation.border
import androidx.compose.ui.platform.LocalView
import com.rws.kittylauncher.data.GlobalConfig
//import com.rws.kittylauncher.data.LocalLauncherUI

@Composable
fun AppCard(
    app: AppEntry,
    isMoving: Boolean,
    isHidden: Boolean,
    accent: Color,
    cardWidth: androidx.compose.ui.unit.Dp = 190.dp,
    showLabel: Boolean = true,
    modifier: Modifier = Modifier,
    jiggleTrigger: Int = 0,  //rws jiggle
    jiggleDirection: Int = 0,
    onLaunch: () -> Unit,
    onLongPress: () -> Unit,
) {
    // Long-press handling. The launcher must never do BOTH actions, and the
    // trap is that releasing OK after a hold still arrives as a normal click
    // on the Surface (its own built-in handler) — which launched the app
    // behind the freshly opened menu. So instead of fighting the key events,
    // we detect the hold ourselves and then SUPPRESS the click that follows
    // it, using a short time window that expires on its own (a sticky flag
    // would eat the next legitimate press, since the release is delivered to
    // the menu's window and never comes back to this card).
    val view = LocalView.current
    val isMuted = LocalMuteNavSounds.current
    val cardShape = SmoothCornerShape(LocalCornerRadius.current)
    var downAt by remember { mutableLongStateOf(0L) }
    var lastKeyDown by remember { mutableLongStateOf(0L) }
    var longPressAt by remember { mutableLongStateOf(0L) }

    //rws jiggle
    val jiggleX = remember { Animatable(0f) }
    val jiggleY = remember { Animatable(0f) }

    LaunchedEffect(jiggleTrigger) {
        if (jiggleTrigger == 0) return@LaunchedEffect

        jiggleX.snapTo(0f)
        jiggleY.snapTo(0f)

        if (jiggleDirection == 2) {
            jiggleY.animateTo(8f, tween(70))
            jiggleY.animateTo(-5f, tween(55))
            jiggleY.animateTo(0f, tween(70))
        } else {
            jiggleX.animateTo(12f, tween(70))
            jiggleX.animateTo(-8f, tween(55))
            jiggleX.animateTo(0f, tween(70))
        }
    }

    fun fireLongPress() {
        longPressAt = SystemClock.uptimeMillis()
        onLongPress()
    }
    //rws focus ring
    val interactionSource = remember { androidx.compose.foundation.interaction.MutableInteractionSource() }
    val isFocused by interactionSource.collectIsFocusedAsState()
    //val ui = LocalLauncherUI.current
    val ui = GlobalConfig.ui
    // Focus: the card grows a touch, lifts on a soft tight shadow, and gains a
    // thin accent ring — crisp to read across a room.
    Surface(
        onClick = {
            // Ignore the click generated by releasing a long press.
            if (SystemClock.uptimeMillis() - longPressAt > 1_000L) {playClickSound(view, isMuted);}; onLaunch()
        },

        onLongClick = {playClickSound(view, isMuted); fireLongPress()}, // pointer / mouse path
        interactionSource = interactionSource, //rws focus ring
        modifier = modifier
            .onPreviewKeyEvent { e ->
                val select = e.key == Key.DirectionCenter || e.key == Key.Enter ||
                    e.key == Key.NumPadEnter
                if (!select || e.type != KeyEventType.KeyDown) return@onPreviewKeyEvent false
                val now = SystemClock.uptimeMillis()
                // Auto-repeats arrive every 50-100ms; a gap >300ms means a new press.
                if (lastKeyDown == 0L || now - lastKeyDown > 300) {
                    downAt = now
                    lastKeyDown = now
                    return@onPreviewKeyEvent false // let the normal click path work
                }
                lastKeyDown = now
                if (now - longPressAt > 1_000L && now - downAt >= 450) {
                    fireLongPress()
                }
                true // swallow the repeats themselves
            }
            //rws jiggle
            .graphicsLayer {
                translationX = jiggleX.value
                translationY = jiggleY.value
            }
            .width(cardWidth),
        shape = ClickableSurfaceDefaults.shape(cardShape),
        colors = ClickableSurfaceDefaults.colors(
            //rws allows for transparency when moving
            //containerColor = app.tile,
            //focusedContainerColor = app.tile,
            containerColor = if (isMoving) app.tile.copy(alpha = ui.appCardContainerMovingAlpha) else app.tile,
            focusedContainerColor = if (isMoving) app.tile.copy(alpha = ui.appCardContainerMovingAlpha) else app.tile,
            contentColor = Color.White,
            focusedContentColor = Color.White,
        ),
        //rws make the focused card larger and purple border
        //scale = ClickableSurfaceDefaults.scale(focusedScale = 1.10f),
        scale = ClickableSurfaceDefaults.scale(
            focusedScale = if (isMoving) ui.appCardFocusedScale else ui.appCardMovingScale
        ),
        glow = ClickableSurfaceDefaults.glow(
            // Softer + tighter than before: reads at 3m, cheap to render on weak
            // TV GPUs, and no longer competes with the accent ring.
            //rws Needs to be larger because of larger borders
            //focusedGlow = Glow(elevationColor = Color.Black.copy(alpha = 0.5f), elevation = 8.dp)
            focusedGlow = Glow(elevationColor = Color.Black.copy(alpha = ui.appCardFocusedGlowAlpha), elevation = ui.appCardFocusedGlowElevationDp.dp)
        ),
        border = ClickableSurfaceDefaults.border(
            // Thin accent ring on focus (thicker while dragging in move mode).
            focusedBorder = Border(
                //rws Red if moving, purple otherwise and bump size of border
                //BorderStroke(if (isMoving) 3.dp else 2.dp, accent),
                BorderStroke(
                    width = if (isMoving) ui.appCardMovingBorderWidthDp.dp else ui.appCardBorderWidthDp.dp,
                    color = if (isMoving) Color(ui.appCardMovingBorderColor) else Color(ui.appCardBorderColor)
                ),
                shape = cardShape,
            )
        ),
    ) {
        Box(
            Modifier
                .fillMaxWidth()
                .aspectRatio(16f / 9f)
                .graphicsLayer {
                    //rws make transparent when moving
                    alpha = if (isMoving) ui.appCardGraphicsLayerMovingAlpha else 1.0f
                }
                //rws focus ring (3.dp inner black ring)
                .then(
                    if (isFocused) {
                        Modifier.border(ui.appCardInnerBlackBorderWidthDp.dp, Color.Black, cardShape)
                    } else Modifier
                )
        ) {
            if (app.banner != null) {
                Image(
                    bitmap = app.banner,
                    contentDescription = app.label,
                    contentScale = ContentScale.Crop,
                    // Own render layer: the focus scale animation transforms the
                    // cached layer instead of re-drawing (re-sampling) the bitmap.
                    modifier = Modifier.fillMaxSize().graphicsLayer { },
                )
            } else {
                // Banner-less apps: give the flat tile depth with a subtle sheen
                // (light top, dark bottom) so it sits next to real banners.
                Box(
                    Modifier
                        .fillMaxSize()
                        .background(
                            androidx.compose.ui.graphics.Brush.verticalGradient(
                                listOf(
                                    Color.White.copy(alpha = 0.10f),
                                    Color.Transparent,
                                    Color.Black.copy(alpha = 0.14f),
                                )
                            )
                        )
                )
                Column(
                    Modifier
                        .fillMaxSize()
                        .padding(8.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
                        if (app.icon != null) {
                            Image(
                                bitmap = app.icon,
                                contentDescription = null,
                                modifier = Modifier.size(48.dp),
                            )
                        }
                    }
                    if (showLabel) {
                        Text(
                            text = app.label,
                            style = MaterialTheme.typography.labelMedium,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                    }
                }
            }
            if (isHidden) {
                Box(
                    Modifier
                        .fillMaxSize()
                        .background(Color.Black.copy(alpha = 0.6f))
                )
            }
        }
    }
}
